require("dotenv").config();
const mongoose = require("mongoose");
const dns = require("dns");
const Product = require("./models/Product");
const Collection = require("./models/Collection");

dns.setServers(["8.8.8.8", "8.8.4.4"]);

const products = [
  {
    id: "1",
    name: "Auricular Gamer Sakura - Edicion Rosa",
    price: 85000,
    image: "auricular",
    images: ["auricular"],
    category: "Periféricos",
    tags: ["new"],
    colors: ["#FEEBEE", "#E8D5E8", "#D5D5F0"],
    description: "Auricular gamer inalambrico con drivers de 50mm y cancelacion de ruido pasiva. Diseno Sakura Edition con iluminacion RGB suave y almohadillas de memory foam.",
    features: [
      "Drivers de 50mm con sonido envolvente",
      "Conectividad inalambrica 2.4GHz",
      "Bateria de hasta 20hs de uso",
      "Microfono retractil con cancelacion de ruido",
      "Almohadillas memory foam recubiertas en tela",
    ],
    rating: 4.9,
    reviews: 87,
  },
  {
    id: "2",
    name: "Auricular Gamer Minimal - Edicion Gris",
    price: 75000,
    originalPrice: 92000,
    image: "auricular2",
    images: ["auricular2"],
    category: "Periféricos",
    tags: ["sale"],
    colors: ["#D0D0D0", "#1a1a1a"],
    description: "Auricular gamer con diseño minimalista en gris carbono. Ideal para sesiones largas gracias a su estructura liviana y almohadillas de espuma de alta densidad.",
    features: [
      "Peso ultraliviano: 250g",
      "Cable trenzado desmontable de 1.5m",
      "Diadema ajustable con padding suave",
      "Respuesta de frecuencia: 20Hz - 20kHz",
      "Conector jack 3.5mm universal",
    ],
    rating: 4.6,
    reviews: 53,
  },
  {
    id: "3",
    name: "PC Case RGB Pink - Full Tower",
    price: 185000,
    image: "case",
    images: ["case"],
    category: "PC Cases",
    tags: ["new", "limited"],
    colors: ["#FEEBEE", "#E8D5E8"],
    description: "Gabinete Full Tower con panel lateral de vidrio templado y sistema de iluminacion RGB integrado en tonos pastel.",
    features: [
      "Panel lateral de vidrio templado",
      "Soporte para 6 ventiladores de 120mm",
      "Iluminacion RGB ARGB integrada",
      "Compatibilidad ATX / MicroATX / ITX",
      "Hub de cables interno incluido",
    ],
    rating: 4.8,
    reviews: 34,
  },
  {
    id: "4",
    name: "PC Case Mesh - Mid Tower",
    price: 155000,
    image: "case2",
    images: ["case2"],
    category: "PC Cases",
    tags: [],
    colors: ["#1a1a1a", "#2a2a2a"],
    description: "Gabinete Mid Tower con panel frontal mesh para maxima ventilacion. Diseño neutro compatible con cualquier setup.",
    features: [
      "Panel frontal mesh de alta densidad",
      "Soporte para 4 ventiladores de 120mm",
      "2 USB 3.0 frontales",
      "Compatible con coolers de hasta 165mm",
    ],
    rating: 4.5,
    reviews: 28,
  },
  {
    id: "5",
    name: "Keycaps Pastel Sakura",
    price: 32000,
    image: "keycap",
    images: ["keycap"],
    category: "Keycaps",
    tags: ["new"],
    colors: ["#FFB3C6", "#B3D9FF", "#B3FFD1", "#FFE5B3"],
    description: "Set de keycaps PBT doble shot en colores pastel inspirados en la flor de cerezo. Compatibles con switches Cherry MX y clones.",
    features: [
      "Material PBT doble shot",
      "Perfil OEM",
      "137 teclas incluidas",
      "Compatible con switches Cherry MX y clones",
    ],
    rating: 4.7,
    reviews: 112,
  },
  {
    id: "6",
    name: "Monitor Curvo 27\" - 165Hz",
    price: 320000,
    image: "monitor",
    images: ["monitor"],
    category: "Monitores",
    tags: ["new"],
    colors: ["#1a1a1a"],
    description: "Monitor curvo 1500R de 27 pulgadas con panel VA, 165Hz y 1ms de respuesta. Ideal para gaming y diseño.",
    features: [
      "Panel VA 27\" curvo 1500R",
      "Resolucion 2560x1440 QHD",
      "165Hz con FreeSync Premium",
      "1ms tiempo de respuesta",
      "HDR10 compatible",
    ],
    rating: 4.9,
    reviews: 67,
  },
  {
    id: "7",
    name: "Mouse Gamer Paw - Wireless",
    price: 68000,
    image: "mouse",
    images: ["mouse"],
    category: "Periféricos",
    tags: ["new"],
    colors: ["#FEEBEE", "#E8D5E8"],
    description: "Mouse gamer inalambrico 2.4GHz con sensor optico de 25600 DPI. Edicion Paw con diseño ergonomico y luces RGB suaves.",
    features: [
      "Sensor optico 25600 DPI",
      "Conexion inalambrica 2.4GHz",
      "Bateria de 70hs de autonomia",
      "6 botones programables",
      "Iluminacion RGB personalizable",
    ],
    rating: 4.8,
    reviews: 94,
  },
  {
    id: "8",
    name: "Mousepad XL Sakura",
    price: 18000,
    image: "mousepad",
    images: ["mousepad"],
    category: "Mousepads",
    tags: [],
    colors: ["#FEEBEE"],
    description: "Mousepad XL con estampado Sakura. Base antideslizante y superficie de tela de alta precision.",
    features: [
      "Tamaño XL: 900x400mm",
      "Superficie de tela premium",
      "Base de goma antideslizante",
      "Bordes cosidos resistentes",
    ],
    rating: 4.6,
    reviews: 145,
  },
  {
    id: "9",
    name: "Stand Heart para celular",
    price: 22000,
    image: "stand",
    images: ["stand"],
    category: "Accesorios",
    tags: [],
    colors: ["#1a1a1a", "#FEEBEE"],
    description: "Soporte para celular acrilico con forma de corazon. Ideal para tener tu telefono a la vista mientras trabajas o juegas.",
    features: [
      "Material acrilico resistente",
      "Diseño en forma de corazon",
      "Base antideslizante",
      "Compatible con la mayoria de smartphones",
    ],
    rating: 4.4,
    reviews: 38,
  },
  {
    id: "10",
    name: "Teclado Mecanico Clear RGB - 60%",
    price: 95000,
    image: "teclado",
    images: ["teclado"],
    category: "Periféricos",
    tags: ["new"],
    colors: ["#FEEBEE", "#E8D5E8"],
    description: "Teclado mecanico 60% con switches tactiles y carcasa transparente para maximizar la iluminacion RGB. Ideal para quienes buscan un teclado con estilo y rendimiento.",
    features: [
      "Switches tactiles 45g",
      "Keycaps PBT doble shot incluidos",
      "Cable USB-C desmontable",
      "Iluminacion RGB por tecla",
      "Layout 60% compacto",
    ],
    rating: 4.9,
    reviews: 76,
  },
  {
    id: "11",
    name: "LED Strip RGB - 3m",
    price: 12000,
    image: "ledstripes",
    images: ["ledstripes"],
    category: "Iluminacion",
    tags: [],
    colors: ["#FF0000", "#00FF00", "#0000FF", "#FFFFFF"],
    description: "Tira LED RGB de 3 metros con control remoto y app. Adhesivo 3M incluido.",
    features: [
      "3 metros de largo",
      "Control via app y remoto IR",
      "16 millones de colores",
      "Adhesivo 3M resistente",
      "Compatible con Alexa y Google Home",
    ],
    rating: 4.3,
    reviews: 203,
  },
  {
    id: "12",
    name: "Teclado Mecanico Sakura - TKL",
    price: 110000,
    image: "teclado2",
    images: ["teclado2"],
    category: "Periféricos",
    tags: ["limited"],
    colors: ["#E8D5E8", "#D5D5F0", "#D5EBE8"],
    description: "Teclado mecanico full size con switches lineales y keycaps en degradado pastel. Edicion limitada.",
    features: [
      "Switches lineales 45g",
      "Layout full size 104 teclas",
      "Keycaps degradado pastel PBT",
      "Knob de volumen incluido",
      "Bluetooth 5.0 + USB-C",
    ],
    rating: 4.8,
    reviews: 41,
  },
  {
    id: "13",
    name: "Mouse Gamer Sakura - Wireless",
    price: 45000,
    originalPrice: 46000,
    image: "mouse2",
    images: ["mouse2"],
    category: "Periféricos",
    tags: ["sale"],
    colors: ["#1a1a1a", "#D0D0D0"],
    description: "Mouse gamer inalambrico con sensor optico de 16000 DPI. Edicion Sakura con diseño moderno y adorable",
    features: [
      "Sensor optico 16000 DPI",
      "Conexion inalambrica 2.4GHz",
      "Bateria de 50hs de autonomia",
      "6 botones programables",
      "Iluminacion RGB personalizable",
    ],
    rating: 4.5,
    reviews: 88,
  },
  {
    id: "14",
    name: "Mousepad Rosa Pastel Liso - Bordes RGB",
    price: 20000,
    image: "mousepad2",
    images: ["mousepad2"],
    category: "Mousepads",
    tags: ["new"],
    colors: ["#E8D5E8"],
    description: "Mousepad rosa pastel con bordes RGB. Superficie de tela suave y base antideslizante para sesiones de juego cómodas y con estilo.",
    features: [
      "Tamaño XL: 900x400mm",
      "Superficie de tela premium",
      "Base de goma antideslizante",
      "Bordes RGB personalizables",
    ],
    rating: 4.7,
    reviews: 99,
  },
  {
    id: "15",
    name: "Silla Gamer Ergonomica - Rosa",
    price: 280000,
    image: "silla",
    images: ["silla"],
    category: "Sillas",
    tags: ["new"],
    colors: ["#FEEBEE", "#1a1a1a"],
    description: "Silla gamer ergonomica con soporte lumbar ajustable y reposabrazos 4D. Tapizado en cuero sintetico rosa.",
    features: [
      "Soporte lumbar y cervical ajustable",
      "Reposabrazos 4D",
      "Reclinable hasta 180 grados",
      "Base de aluminio pulido",
      "Capacidad hasta 150kg",
    ],
    rating: 4.6,
    reviews: 57,
  },
];

const collections = [
  {
    id: "sakura-set",
    name: "Sakura Set",
    tagline: "El setup que florece",
    description: "Una coleccion pensada para quienes quieren un setup coherente en tonos rosa pastel. Audio, control y teclado en una sola paleta.",
    coverImage: "teclado2",
    accentColor: "from-pink-100 to-rose-50",
    productIds: ["12", "1", "13"],
    tags: ["pastel", "pink", "completo"],
  },
  {
    id: "rgb-build",
    name: "RGB Build",
    tagline: "Todos miran tu brillo",
    description: "Case, iluminación y teclado RGB para armar un setup que brilla desde adentro hacia afuera.",
    coverImage: "mousepad2",
    accentColor: "from-purple-50 to-pink-50",
    productIds: ["10", "11", "3"],
    tags: ["desk", "iluminacion", "aesthetic"],
  },
  {
    id: "all-in",
    name: "All in Setup",
    tagline: "Comenzá acá",
    description: "Case, Monitor y silla. Los escenciales para transformar tu espacio.",
    coverImage: "case",
    accentColor: "from-violet-50 to-purple-50",
    productIds: ["4", "6", "15"],
    tags: ["rgb", "build", "gaming"],
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Conectado a MongoDB");

    await Product.deleteMany({});
    await Collection.deleteMany({});
    console.log("🗑️  Datos anteriores limpiados");

    await Product.insertMany(products);
    console.log(`✅ ${products.length} productos insertados`);

    await Collection.insertMany(collections);
    console.log(`✅ ${collections.length} colecciones insertadas`);

    console.log("🎉 Seed completado!");
  } catch (err) {
    console.error("❌ Error en seed:", err);
  } finally {
    mongoose.disconnect();
  }
}

seed();